// this file is generated by servgen util based on a template at 2021-06-26 10:37:24 +0300 MSK
package domain

import (
	"context"
	"time"
)

type Activity struct {
	Id        string     `json:"id"`         // Id - unique identifier
	Owner     string     `json:"owner"`      // Owner user id
	Type	  string     `json:"type"`       // Type activity type id
	Family    string     `json:"family"`     // Family owner family id
	DateFrom  time.Time  `json:"date_from"`  // DateFrom start of the task
	DateTo    time.Time  `json:"date_to"`    // DateTo end of the task
}

type ActivityType struct {
	Id          string     `json:"id"`           // Id - unique identifier
	Family      string     `json:"family"`    // Family - Family owning activity type
	Name        string     `json:"name"`         // Name activity name
	Description string     `json:"description"`  // Description activity description
}

type ActivityService interface {
	// Create creates a new Activity
	Create(ctx context.Context, activity *Activity) (*Activity, error)
	// Update updates an existent Activity
	Update(ctx context.Context, activity *Activity) (*Activity, error)
	// Get retrieves an Activity by id
	Get(ctx context.Context, id string) (bool, *Activity, error)
	// ListActivities lists all Activities owned by user
	ListActivities(ctx context.Context, userId string) (bool, []*Activity, error)
	//ListActivitiesByFamily retrieves all activities done by all Family members
	ListActivitiesByFamily(ctx context.Context, familyId string) (bool, []*Activity, error)
	// Delete deletes an Activity
	Delete(ctx context.Context, id string) error
	// CreateActivityType creates a new ActivityType
	CreateActivityType(ctx context.Context, activityType *ActivityType) (*ActivityType, error)
	// UpdateActivityType updates an existent ActivityType
	UpdateActivityType(ctx context.Context, activityType *ActivityType) (*ActivityType, error)
	// GetActivityType retrieves an ActivityType by id
	GetActivityType(ctx context.Context, id string) (bool, *ActivityType, error)
	// ListActivityTypes lists all Activities owned by Family of the user
	ListActivityTypes(ctx context.Context, familyId string) (bool, []*ActivityType, error)
	// DeleteActivityType deletes an ActivityType by id
	DeleteActivityType(ctx context.Context, id string) error
}
