// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/turbulent376/homeactivity/activity/internal/domain"
)

// ActivityService is an autogenerated mock type for the ActivityService type
type ActivityService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, activity
func (_m *ActivityService) Create(ctx context.Context, activity *domain.Activity) (*domain.Activity, error) {
	ret := _m.Called(ctx, activity)

	var r0 *domain.Activity
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Activity) *domain.Activity); ok {
		r0 = rf(ctx, activity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Activity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Activity) error); ok {
		r1 = rf(ctx, activity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateActivityType provides a mock function with given fields: ctx, activityType
func (_m *ActivityService) CreateActivityType(ctx context.Context, activityType *domain.ActivityType) (*domain.ActivityType, error) {
	ret := _m.Called(ctx, activityType)

	var r0 *domain.ActivityType
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ActivityType) *domain.ActivityType); ok {
		r0 = rf(ctx, activityType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ActivityType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.ActivityType) error); ok {
		r1 = rf(ctx, activityType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ActivityService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteActivityType provides a mock function with given fields: ctx, id
func (_m *ActivityService) DeleteActivityType(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *ActivityService) Get(ctx context.Context, id string) (bool, *domain.Activity, error) {
	ret := _m.Called(ctx, id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 *domain.Activity
	if rf, ok := ret.Get(1).(func(context.Context, string) *domain.Activity); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.Activity)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetActivityType provides a mock function with given fields: ctx, id
func (_m *ActivityService) GetActivityType(ctx context.Context, id string) (bool, *domain.ActivityType, error) {
	ret := _m.Called(ctx, id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 *domain.ActivityType
	if rf, ok := ret.Get(1).(func(context.Context, string) *domain.ActivityType); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.ActivityType)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListActivities provides a mock function with given fields: ctx, userId
func (_m *ActivityService) ListActivities(ctx context.Context, userId string) (bool, []*domain.Activity, error) {
	ret := _m.Called(ctx, userId)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 []*domain.Activity
	if rf, ok := ret.Get(1).(func(context.Context, string) []*domain.Activity); ok {
		r1 = rf(ctx, userId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*domain.Activity)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, userId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListActivitiesByFamily provides a mock function with given fields: ctx, familyId
func (_m *ActivityService) ListActivitiesByFamily(ctx context.Context, familyId string) (bool, []*domain.Activity, error) {
	ret := _m.Called(ctx, familyId)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, familyId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 []*domain.Activity
	if rf, ok := ret.Get(1).(func(context.Context, string) []*domain.Activity); ok {
		r1 = rf(ctx, familyId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*domain.Activity)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, familyId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListActivityTypes provides a mock function with given fields: ctx, familyId
func (_m *ActivityService) ListActivityTypes(ctx context.Context, familyId string) (bool, []*domain.ActivityType, error) {
	ret := _m.Called(ctx, familyId)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, familyId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 []*domain.ActivityType
	if rf, ok := ret.Get(1).(func(context.Context, string) []*domain.ActivityType); ok {
		r1 = rf(ctx, familyId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*domain.ActivityType)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, familyId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, activity
func (_m *ActivityService) Update(ctx context.Context, activity *domain.Activity) (*domain.Activity, error) {
	ret := _m.Called(ctx, activity)

	var r0 *domain.Activity
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Activity) *domain.Activity); ok {
		r0 = rf(ctx, activity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Activity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Activity) error); ok {
		r1 = rf(ctx, activity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateActivityType provides a mock function with given fields: ctx, activityType
func (_m *ActivityService) UpdateActivityType(ctx context.Context, activityType *domain.ActivityType) (*domain.ActivityType, error) {
	ret := _m.Called(ctx, activityType)

	var r0 *domain.ActivityType
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ActivityType) *domain.ActivityType); ok {
		r0 = rf(ctx, activityType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ActivityType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.ActivityType) error); ok {
		r1 = rf(ctx, activityType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
