http:
  port: ${API_HTTP_PORT|8000}
  allowedOrigins:
    - "*"
  allowedMethods:
    - GET
    - POST
    - PUT
    - DELETE
  allowedHeaders:
    - RequestId
  debug: ${API_HTTP_CORS_DEBUG|false}

log:
  format: ${API_LOG_FORMAT|plain}
  level: ${API_LOG_LEVEL|trace}

adapters:
  auth:
    grpc:
      host: ${AUTH_GRPC_HOST|localhost}
      port: ${AUTH_GRPC_PORT|50060}
  billing:
    grpc:
      host: ${BILLING_GRPC_HOST|localhost}
      port: ${BILLING_GRPC_PORT|50061}
  report:
    grpc:
      host: ${REPORT_GRPC_HOST|localhost}
      port: ${REPORT_GRPC_PORT|50065}
  storage:
    grpc:
      host: ${STORAGE_GRPC_HOST|localhost}
      port: ${STORAGE_GRPC_PORT|50064}
  timesheet:
    grpc:
      host: ${TIMESHEET_GRPC_HOST|localhost}
      port: ${TIMESHEET_GRPC_PORT|50066}
  location:
    grpc:
      host: ${LOCATION_GRPC_HOST|localhost}
      port: ${LOCATION_GRPC_PORT|50062}