http:
  port: ${API_HTTP_PORT|8000}
  allowedOrigins:
    - "*"
  allowedMethods:
    - GET
    - POST
    - PUT
    - DELETE
  allowedHeaders:
    - RequestId
  debug: ${API_HTTP_CORS_DEBUG|false}

log:
  format: ${API_LOG_FORMAT|plain}
  level: ${API_LOG_LEVEL|trace}

adapters:
  auth:
    grpc:
      host: ${AUTH_GRPC_HOST|localhost}
      port: ${AUTH_GRPC_PORT|50060}
  activity:
    grpc:
      host: ${ACTIVITY_GRPC_HOST|localhost}
      port: ${ACTIVITY_GRPC_PORT|50066}